- name: configuring frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: present


  - name: installing nginx
    ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes  


  - name: Delete content & directory
    ansible.builtin.file:
     state: absent
     path:    /usr/share/nginx/html


  - name: Download the code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip


