- name: configuring frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: present


  - name: installing nginx
    ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes  


